from core.constants import *


ALERT_DURATION_FRAMES = int(50 * (FRAME_RATE / 30))
WAIT_AFTER_BAR_FRAMES = int(30 * (FRAME_RATE / 30))
IMPACT_DURATION_FRAMES = int(60 * (FRAME_RATE / 30))
WAIT_ATTACK_READY_FRAMES = int(20 * (FRAME_RATE / 30))
RESULT_SCREEN_FRAMES = int(90 * (FRAME_RATE / 30))
BAR_HOLD_TIME_MS = 2500
ATTACK_SPEED = 4 * (SCREEN_WIDTH / 240)

ENEMY_ENTRY_SPEED = 1 * (SCREEN_WIDTH / 240)
IDLE_ANIM_DURATION = int(90 * (FRAME_RATE / 30))
ALERT_FRAME_DELAY = int(10 * (FRAME_RATE / 30))
AFTER_ATTACK_DELAY_FRAMES = int(50 * (FRAME_RATE / 30))
LEVEL_DURATION_FRAMES = int(60 * (FRAME_RATE / 30))

READY_FRAME_COUNTER = int(60 * (FRAME_RATE / 30))
ALERT_FRAME_COUNTER = int(90 * (FRAME_RATE / 30))